libname mylib "/folders/myshortcuts/silsup/week2";
data tmp1;
	infile "/folders/myshortcuts/silsup/week2/score1.txt";
		input gender $ kor eng mat sci;
run;
data tmp2;
		infile "/folders/myshortcuts/silsup/week2/score.txt" ;
		input gender $ kor eng mat sci;
run;
data mylib.homework1;
	set tmp1 tmp2;
	total = kor*2 + eng*2 + mat + sci*2;
	if (total >= 400) then note = "GREAT";
	else if(total >= 300) then note = "GOOD";
	else if(total >= 200) then note = "BAD";
	else note = "FAIL";
	drop kor eng mat sci;
run;
title 'HW1-황세현(2016004011)';
proc print data=mylib.homework1;
run;