Data bb_data;
	SET SASHELP.BASEBALL;
RUN;
Data heart_data  ;
	options obs=1000;
	set SASHELP.HEART;
	if Weight_Status="Overweight" then ws=1;
	else if Weight_Status="Normal" then ws=0;
	else ws=-1;
	keep ws Cholesterol;
RUN;
proc corr data=bb_data;
	var nAtBat nHits;
run;
proc corr data=bb_data PLOTS=matrix;
	var nAtBat nHits;
run;
proc corr data=heart_data ;
	var ws Cholesterol;
run;
proc corr data=heart_data PLOTS=matrix;
	var ws Cholesterol;
run;