libname mylib "/folders/myshortcuts/silsup/week2";
data tmp1;
	infile "/folders/myshortcuts/silsup/week2/score1.txt";
		input gender $ kor eng mat sci;
run;
data tmp2;
		infile "/folders/myshortcuts/silsup/week2/score.txt" ;
		input gender $ kor eng mat sci;
run;
data tmp3;
		infile "/folders/myshortcuts/silsup/week2/pass.txt" ;
		input gender $ pass $;
		if pass="합격" then pass="T";
		else pass="F";
run;
data mylib.silsup1;
		set tmp1 tmp2; 
		merge mylib.silsup1 tmp3;
		total = kor + eng + mat + sci;
run;
